baseURL = "https://nguyencatpham.github.io/blog/"
languageCode = "en-us"
title = "Nguyen Cat Pham's Blog"
theme = "wangchucheng.com/hugo-eureka"

[params]
  author = "Nguyen Cat Pham"
  description = "A blog about all things technical."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/nguyencatpham"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/nguyencatpham"